import { BodyDefinition } from './types';
import { DISTANCE_SCALE_KM } from '../config/constants';

function moonDefinition(
  id: string,
  horizonsId: number,
  name: string,
  parentId: string,
  radiusKm: number,
  labelColor: string,
  semiMajorAxisKm: number,
  eccentricity: number,
  inclination: number,
  ma0: number,
  periodDays: number,
): BodyDefinition {
  return {
    id,
    horizonsId,
    name,
    type: 'moon',
    parentId,
    radiusKm,
    labelColor,
    textures: {
      placeholder: labelColor,
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    rotation: {
      periodHours: periodDays * 24,
      axialTiltDeg: inclination,
    },
    keplerianElements: {
      a: semiMajorAxisKm / DISTANCE_SCALE_KM,
      e: eccentricity,
      inclination,
      omega: 0,
      raan: 0,
      ma0,
    },
    periodDays,
  };
}

/**
 * Canonical registry of all solar system bodies known to the app.
 *
 * Keplerian elements use J2000.0 epoch (2000-Jan-01 12:00 TT) with:
 *   a         — semi-major axis in scene units (km / DISTANCE_SCALE_KM)
 *   angles    — degrees
 *   ma0       — mean anomaly at J2000, degrees (from JPL approximate elements)
 *
 * Ephemeris JSON files (public/ephemeris/<id>.json) generated by
 * scripts/fetchEphemeris.mjs take precedence over these elements at runtime.
 */
export const BODIES: Record<string, BodyDefinition> = {
  mercury: {
    id: 'mercury',
    horizonsId: 199,
    name: 'Mercury',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 2439.7,
    labelColor: '#b5b5b5',
    textures: {
      placeholder: '#b5b5b5',
      low: '/textures/lod/8k_mercury_1k.jpg',
      high: '/textures/8k_mercury.jpg',
    },
    keplerianElements: {
      a: 5.79091e7 / DISTANCE_SCALE_KM,
      e: 0.20564,
      inclination: 7.01,
      omega: 29.022,
      raan: 48.378,
      ma0: 174.796,
    },
    periodDays: 87.97,
    rotation: {
      periodHours: 1407.6,
      axialTiltDeg: 0.01,
    },
  },

  venus: {
    id: 'venus',
    horizonsId: 299,
    name: 'Venus',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 6051.8,
    labelColor: '#e8cda0',
    textures: {
      placeholder: '#e8cda0',
      low: '/textures/lod/8k_venus_surface_1k.jpg',
      high: '/textures/8k_venus_surface.jpg',
    },
    keplerianElements: {
      a: 1.08209e8 / DISTANCE_SCALE_KM,
      e: 0.00676,
      inclination: 3.395,
      omega: 131.532,
      raan: 76.681,
      ma0: 50.415,
    },
    periodDays: 224.70,
    rotation: {
      periodHours: -5832.5,
      axialTiltDeg: 177.4,
    },
  },

  earth: {
    id: 'earth',
    horizonsId: 399,
    name: 'Earth',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 6371.0,
    labelColor: '#4fb8ff',
    textures: {
      placeholder: '#4fb8ff',
      low: '/textures/lod/8k_earth_daymap_1k.jpg',
      high: '/textures/8k_earth_daymap.jpg',
    },
    keplerianElements: {
      a: 1.49598e8 / DISTANCE_SCALE_KM,
      e: 0.0167,
      inclination: 0.0,
      omega: 102.947,
      raan: -11.260,
      ma0: 357.517,
    },
    periodDays: 365.256,
    rotation: {
      periodHours: 23.9345,
      axialTiltDeg: 23.4,
    },
  },

  moon: {
    id: 'moon',
    horizonsId: 301,
    name: 'Moon',
    type: 'moon',
    parentId: 'earth',
    radiusKm: 1737.4,
    labelColor: '#c8c8c8',
    textures: {
      placeholder: '#c8c8c8',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      // Distance from Earth (geocentric)
      a: 384400 / DISTANCE_SCALE_KM,
      e: 0.0549,
      inclination: 5.145,
      omega: 318.0,
      raan: 125.0,
      ma0: 135.27,
    },
    periodDays: 27.321582,
    rotation: {
      periodHours: 655.7,
      axialTiltDeg: 6.7,
    },
  },

  mars: {
    id: 'mars',
    horizonsId: 499,
    name: 'Mars',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 3389.5,
    labelColor: '#c1440e',
    textures: {
      placeholder: '#c1440e',
      low: '/textures/lod/8k_mars_1k.jpg',
      high: '/textures/8k_mars.jpg',
    },
    keplerianElements: {
      a: 2.27956e8 / DISTANCE_SCALE_KM,
      e: 0.0935,
      inclination: 1.848,
      omega: 336.04,
      raan: 49.579,
      ma0: 19.412,
    },
    periodDays: 686.980,
    rotation: {
      periodHours: 24.623,
      axialTiltDeg: 25.2,
    },
  },

  jupiter: {
    id: 'jupiter',
    horizonsId: 599,
    name: 'Jupiter',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 69911,
    labelColor: '#c88b3a',
    textures: {
      placeholder: '#c88b3a',
      low: '/textures/lod/8k_jupiter_1k.jpg',
      high: '/textures/8k_jupiter.jpg',
    },
    keplerianElements: {
      a: 7.78479e8 / DISTANCE_SCALE_KM,
      e: 0.0487,
      inclination: 1.305,
      omega: 14.754,
      raan: 100.556,
      ma0: 20.020,
    },
    periodDays: 4332.589,
    rotation: {
      periodHours: 9.925,
      axialTiltDeg: 3.1,
    },
  },

  saturn: {
    id: 'saturn',
    horizonsId: 699,
    name: 'Saturn',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 58232,
    labelColor: '#e4d191',
    textures: {
      placeholder: '#e4d191',
      low: '/textures/lod/8k_saturn_1k.jpg',
      high: '/textures/8k_saturn.jpg',
    },
    keplerianElements: {
      a: 14.32041e8 / DISTANCE_SCALE_KM,
      e: 0.0520,
      inclination: 2.486,
      omega: 92.432,
      raan: 113.715,
      ma0: 317.020,
    },
    periodDays: 10755.699,
    rotation: {
      periodHours: 10.656,
      axialTiltDeg: 26.7,
    },
  },

  uranus: {
    id: 'uranus',
    horizonsId: 799,
    name: 'Uranus',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 25362,
    labelColor: '#7de8e8',
    textures: {
      placeholder: '#7de8e8',
      low: '/textures/lod/2k_uranus_1k.jpg',
      high: '/textures/2k_uranus.jpg',
    },
    keplerianElements: {
      a: 28.67043e8 / DISTANCE_SCALE_KM,
      e: 0.0469,
      inclination: 0.770,
      omega: 170.964,
      raan: 74.230,
      ma0: 142.955,
    },
    periodDays: 30685.400,
    rotation: {
      periodHours: -17.24,
      axialTiltDeg: 97.8,
    },
  },

  neptune: {
    id: 'neptune',
    horizonsId: 899,
    name: 'Neptune',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 24622,
    labelColor: '#3f54ba',
    textures: {
      placeholder: '#3f54ba',
      low: '/textures/lod/2k_neptune_1k.jpg',
      high: '/textures/2k_neptune.jpg',
    },
    keplerianElements: {
      a: 45.1495e8 / DISTANCE_SCALE_KM,
      e: 0.0097,
      inclination: 1.770,
      omega: 44.971,
      raan: 131.722,
      ma0: 259.905,
    },
    periodDays: 60189,
    rotation: {
      periodHours: 16.11,
      axialTiltDeg: 28.3,
    },
  },

  pluto: {
    id: 'pluto',
    horizonsId: 999,
    name: 'Pluto',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 1188.3,
    labelColor: '#c8ac93',
    textures: {
      placeholder: '#c8ac93',
      low: '/textures/lod/pluto_1k.jpg',
      high: '/textures/pluto.jpg',
    },
    keplerianElements: {
      a: 5.90638e9 / DISTANCE_SCALE_KM,
      e: 0.24880766,
      inclination: 17.14175,
      omega: 113.76329,
      raan: 110.30347,
      ma0: 14.86205,
    },
    periodDays: 90561.6,
    rotation: {
      periodHours: -153.282,
      axialTiltDeg: 57.5,
    },
  },

  phobos: {
    id: 'phobos',
    horizonsId: 401,
    name: 'Phobos',
    type: 'moon',
    parentId: 'mars',
    radiusKm: 11.1,
    labelColor: '#9b8f84',
    textures: {
      placeholder: '#9b8f84',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 9376 / DISTANCE_SCALE_KM,
      e: 0.0151,
      inclination: 1.093,
      omega: 0,
      raan: 0,
      ma0: 35,
    },
    periodDays: 0.31891,
    model: {
      path: '/models/moons/phobos.glb',
      credit: 'NASA/JPL-Caltech',
    },
  },

  deimos: {
    id: 'deimos',
    horizonsId: 402,
    name: 'Deimos',
    type: 'moon',
    parentId: 'mars',
    radiusKm: 6.2,
    labelColor: '#aaa19a',
    textures: {
      placeholder: '#aaa19a',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 23463 / DISTANCE_SCALE_KM,
      e: 0.00033,
      inclination: 0.93,
      omega: 0,
      raan: 0,
      ma0: 140,
    },
    periodDays: 1.26244,
    model: {
      path: '/models/moons/deimos.glb',
      credit: 'NASA/JPL-Caltech',
    },
  },

  io: {
    id: 'io',
    horizonsId: 501,
    name: 'Io',
    type: 'moon',
    parentId: 'jupiter',
    radiusKm: 1821.6,
    labelColor: '#d9b15f',
    textures: {
      placeholder: '#d9b15f',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 421700 / DISTANCE_SCALE_KM,
      e: 0.0041,
      inclination: 0.05,
      omega: 0,
      raan: 0,
      ma0: 20,
    },
    periodDays: 1.76914,
  },

  europa: {
    id: 'europa',
    horizonsId: 502,
    name: 'Europa',
    type: 'moon',
    parentId: 'jupiter',
    radiusKm: 1560.8,
    labelColor: '#d8c7a4',
    textures: {
      placeholder: '#d8c7a4',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 671034 / DISTANCE_SCALE_KM,
      e: 0.0094,
      inclination: 0.47,
      omega: 0,
      raan: 0,
      ma0: 90,
    },
    periodDays: 3.55118,
  },

  ganymede: {
    id: 'ganymede',
    horizonsId: 503,
    name: 'Ganymede',
    type: 'moon',
    parentId: 'jupiter',
    radiusKm: 2634.1,
    labelColor: '#b6aa96',
    textures: {
      placeholder: '#b6aa96',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 1070412 / DISTANCE_SCALE_KM,
      e: 0.0013,
      inclination: 0.2,
      omega: 0,
      raan: 0,
      ma0: 180,
    },
    periodDays: 7.15455,
  },

  callisto: {
    id: 'callisto',
    horizonsId: 504,
    name: 'Callisto',
    type: 'moon',
    parentId: 'jupiter',
    radiusKm: 2410.3,
    labelColor: '#8d8170',
    textures: {
      placeholder: '#8d8170',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 1882709 / DISTANCE_SCALE_KM,
      e: 0.0074,
      inclination: 0.192,
      omega: 0,
      raan: 0,
      ma0: 270,
    },
    periodDays: 16.68902,
  },

  titan: {
    id: 'titan',
    horizonsId: 606,
    name: 'Titan',
    type: 'moon',
    parentId: 'saturn',
    radiusKm: 2574.7,
    labelColor: '#c99252',
    textures: {
      placeholder: '#c99252',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 1221870 / DISTANCE_SCALE_KM,
      e: 0.0288,
      inclination: 0.349,
      omega: 0,
      raan: 0,
      ma0: 60,
    },
    periodDays: 15.94542,
  },

  titania: {
    id: 'titania',
    horizonsId: 703,
    name: 'Titania',
    type: 'moon',
    parentId: 'uranus',
    radiusKm: 788.9,
    labelColor: '#b9b9b9',
    textures: {
      placeholder: '#b9b9b9',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 436300 / DISTANCE_SCALE_KM,
      e: 0.0011,
      inclination: 0.079,
      omega: 0,
      raan: 0,
      ma0: 145,
    },
    periodDays: 8.70587,
  },

  oberon: {
    id: 'oberon',
    horizonsId: 704,
    name: 'Oberon',
    type: 'moon',
    parentId: 'uranus',
    radiusKm: 761.4,
    labelColor: '#9c9994',
    textures: {
      placeholder: '#9c9994',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 583500 / DISTANCE_SCALE_KM,
      e: 0.0014,
      inclination: 0.068,
      omega: 0,
      raan: 0,
      ma0: 235,
    },
    periodDays: 13.46323,
  },

  triton: {
    id: 'triton',
    horizonsId: 801,
    name: 'Triton',
    type: 'moon',
    parentId: 'neptune',
    radiusKm: 1353.4,
    labelColor: '#d0c8bc',
    textures: {
      placeholder: '#d0c8bc',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 354759 / DISTANCE_SCALE_KM,
      e: 0.000016,
      inclination: 156.865,
      omega: 0,
      raan: 0,
      ma0: 310,
    },
    periodDays: 5.87685,
  },

  adrastea: moonDefinition('adrastea', 515, 'Adrastea', 'jupiter', 8.2, '#8d8072', 129000, 0.0018, 0.03, 35, 0.29826),
  metis: moonDefinition('metis', 516, 'Metis', 'jupiter', 21.5, '#9c8975', 128000, 0.0002, 0.06, 82, 0.29478),
  amalthea: moonDefinition('amalthea', 505, 'Amalthea', 'jupiter', 83.5, '#b26a55', 181400, 0.0032, 0.37, 145, 0.49818),
  thebe: moonDefinition('thebe', 514, 'Thebe', 'jupiter', 49.3, '#947864', 221900, 0.0175, 1.08, 230, 0.67454),

  pan: moonDefinition('pan', 618, 'Pan', 'saturn', 14.1, '#b6aa97', 133584, 0.0000, 0.00, 18, 0.57505),
  daphnis: moonDefinition('daphnis', 635, 'Daphnis', 'saturn', 3.8, '#bdb3a2', 136505, 0.0000, 0.00, 48, 0.59408),
  atlas: moonDefinition('atlas', 615, 'Atlas', 'saturn', 15.1, '#afa591', 137670, 0.0012, 0.00, 70, 0.60169),
  prometheus: moonDefinition('prometheus', 616, 'Prometheus', 'saturn', 43.1, '#b7ad9d', 139380, 0.0022, 0.01, 96, 0.61299),
  pandora: moonDefinition('pandora', 617, 'Pandora', 'saturn', 40.7, '#aaa08f', 141720, 0.0042, 0.05, 130, 0.62850),
  epimetheus: moonDefinition('epimetheus', 611, 'Epimetheus', 'saturn', 58.1, '#bdb4a4', 151422, 0.0098, 0.34, 164, 0.69433),
  janus: moonDefinition('janus', 610, 'Janus', 'saturn', 89.5, '#c2b8aa', 151472, 0.0068, 0.16, 210, 0.69466),
  mimas: moonDefinition('mimas', 601, 'Mimas', 'saturn', 198.2, '#bdb9ae', 185539, 0.0196, 1.57, 250, 0.94242),
  enceladus: moonDefinition('enceladus', 602, 'Enceladus', 'saturn', 252.1, '#d7d9d2', 238042, 0.0047, 0.01, 300, 1.37022),
  tethys: moonDefinition('tethys', 603, 'Tethys', 'saturn', 531.1, '#c9c5ba', 294672, 0.0001, 1.09, 20, 1.88780),
  telesto: moonDefinition('telesto', 613, 'Telesto', 'saturn', 12.4, '#bfb7aa', 294672, 0.0002, 1.16, 72, 1.88780),
  calypso: moonDefinition('calypso', 614, 'Calypso', 'saturn', 10.7, '#b8b0a3', 294672, 0.0005, 1.47, 132, 1.88780),
  dione: moonDefinition('dione', 604, 'Dione', 'saturn', 561.4, '#c8c4ba', 377415, 0.0022, 0.02, 182, 2.73692),
  helene: moonDefinition('helene', 612, 'Helene', 'saturn', 16.0, '#b7b0a2', 377415, 0.0022, 0.21, 228, 2.73692),
  rhea: moonDefinition('rhea', 605, 'Rhea', 'saturn', 763.8, '#c3c0b6', 527108, 0.0010, 0.35, 276, 4.51821),
  hyperion: moonDefinition('hyperion', 607, 'Hyperion', 'saturn', 135.0, '#a69780', 1481100, 0.1042, 0.43, 326, 21.27661),
  iapetus: moonDefinition('iapetus', 608, 'Iapetus', 'saturn', 734.5, '#9b8e7c', 3560820, 0.0283, 15.47, 42, 79.32150),
  phoebe: moonDefinition('phoebe', 609, 'Phoebe', 'saturn', 106.5, '#77716c', 12947780, 0.1634, 175.00, 118, 550.48),

  miranda: moonDefinition('miranda', 705, 'Miranda', 'uranus', 235.8, '#b9b6af', 129390, 0.0013, 4.34, 33, 1.41348),
  ariel: moonDefinition('ariel', 701, 'Ariel', 'uranus', 578.9, '#c7c7c0', 191020, 0.0012, 0.04, 92, 2.52038),
  umbriel: moonDefinition('umbriel', 702, 'Umbriel', 'uranus', 584.7, '#8f8f89', 266300, 0.0039, 0.13, 151, 4.14418),
  puck: moonDefinition('puck', 715, 'Puck', 'uranus', 81.0, '#9d9d96', 86010, 0.0001, 0.32, 212, 0.76183),
  portia: moonDefinition('portia', 712, 'Portia', 'uranus', 67.6, '#97978f', 66097, 0.0001, 0.06, 270, 0.51320),

  naiad: moonDefinition('naiad', 803, 'Naiad', 'neptune', 30.2, '#8d98ac', 48227, 0.0003, 4.75, 24, 0.29440),
  thalassa: moonDefinition('thalassa', 804, 'Thalassa', 'neptune', 40.7, '#909bad', 50075, 0.0002, 0.21, 88, 0.31148),
  despina: moonDefinition('despina', 805, 'Despina', 'neptune', 75.0, '#8a95a6', 52526, 0.0002, 0.07, 146, 0.33466),
  galatea: moonDefinition('galatea', 806, 'Galatea', 'neptune', 88.0, '#95a0af', 61953, 0.0001, 0.05, 203, 0.42875),
  larissa: moonDefinition('larissa', 807, 'Larissa', 'neptune', 97.0, '#8d99aa', 73548, 0.0014, 0.20, 260, 0.55465),
  proteus: moonDefinition('proteus', 808, 'Proteus', 'neptune', 210.0, '#9da4ad', 117647, 0.0005, 0.04, 314, 1.12231),
  nereid: moonDefinition('nereid', 802, 'Nereid', 'neptune', 170.0, '#8b8a83', 5513400, 0.7507, 7.23, 62, 360.14),
};

/** All planet ids in order from Sun */
export const PLANET_IDS = [
  'mercury', 'venus', 'earth', 'mars',
  'jupiter', 'saturn', 'uranus', 'neptune', 'pluto',
] as const;

/** Moon ids rendered when their parent planet is focused/nearby. */
export const RENDERED_MOON_IDS = [
  'moon',
  'phobos', 'deimos',
  'adrastea', 'metis', 'amalthea', 'thebe',
  'io', 'europa', 'ganymede', 'callisto',
  'pan', 'daphnis', 'atlas', 'prometheus', 'pandora',
  'epimetheus', 'janus', 'mimas', 'enceladus', 'tethys',
  'telesto', 'calypso', 'dione', 'helene', 'rhea',
  'titan', 'hyperion', 'iapetus', 'phoebe',
  'puck', 'miranda', 'ariel', 'umbriel', 'titania', 'oberon', 'portia',
  'naiad', 'thalassa', 'despina', 'galatea', 'larissa',
  'proteus', 'triton', 'nereid',
] as const;

export const MOON_IDS_BY_PARENT = {
  earth: ['moon'],
  mars: ['phobos', 'deimos'],
  jupiter: ['adrastea', 'metis', 'amalthea', 'thebe', 'io', 'europa', 'ganymede', 'callisto'],
  saturn: [
    'pan', 'daphnis', 'atlas', 'prometheus', 'pandora',
    'epimetheus', 'janus', 'mimas', 'enceladus', 'tethys',
    'telesto', 'calypso', 'dione', 'helene', 'rhea',
    'titan', 'hyperion', 'iapetus', 'phoebe',
  ],
  uranus: ['puck', 'miranda', 'ariel', 'umbriel', 'titania', 'oberon', 'portia'],
  neptune: ['naiad', 'thalassa', 'despina', 'galatea', 'larissa', 'proteus', 'triton', 'nereid'],
  pluto: [],
} as const;

/** Confirmed planetary moon counts from JPL SSD discovery circumstances. */
export const PLANET_MOON_COUNTS = {
  mercury: 0,
  venus: 0,
  earth: 1,
  mars: 2,
  jupiter: 115,
  saturn: 292,
  uranus: 29,
  neptune: 16,
  pluto: 5,
} as const;

/** Body ids with checked-in Horizons JSON files. Other rendered moons use fallback elements. */
export const EPHEMERIS_BODY_IDS = [
  ...PLANET_IDS,
  'moon',
  'phobos', 'deimos',
  'io', 'europa', 'ganymede', 'callisto',
  'titan',
  'titania', 'oberon',
  'triton',
] as const;

/** Top-level body ids that are safe to preload in the background. */
export const PRELOAD_BODY_IDS = [...PLANET_IDS, 'moon'] as const;

/** All body ids known to the app. */
export const ALL_BODY_IDS = [...PLANET_IDS, ...RENDERED_MOON_IDS] as const;
