import { BodyDefinition } from './types';
import { DISTANCE_SCALE_KM } from '../config/constants';

/**
 * Canonical registry of all solar system bodies known to the app.
 *
 * Keplerian elements use J2000.0 epoch (2000-Jan-01 12:00 TT) with:
 *   a         — semi-major axis in scene units (km / DISTANCE_SCALE_KM)
 *   angles    — degrees
 *   ma0       — mean anomaly at J2000, degrees (from JPL approximate elements)
 *
 * Ephemeris JSON files (public/ephemeris/<id>.json) generated by
 * scripts/fetchEphemeris.mjs take precedence over these elements at runtime.
 */
export const BODIES: Record<string, BodyDefinition> = {
  mercury: {
    id: 'mercury',
    horizonsId: 199,
    name: 'Mercury',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 2439.7,
    labelColor: '#b5b5b5',
    textures: {
      placeholder: '#b5b5b5',
      low: '/textures/lod/8k_mercury_1k.jpg',
      high: '/textures/8k_mercury.jpg',
    },
    keplerianElements: {
      a: 5.79091e7 / DISTANCE_SCALE_KM,
      e: 0.20564,
      inclination: 7.01,
      omega: 29.022,
      raan: 48.378,
      ma0: 174.796,
    },
    periodDays: 87.97,
  },

  venus: {
    id: 'venus',
    horizonsId: 299,
    name: 'Venus',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 6051.8,
    labelColor: '#e8cda0',
    textures: {
      placeholder: '#e8cda0',
      low: '/textures/lod/8k_venus_surface_1k.jpg',
      high: '/textures/8k_venus_surface.jpg',
    },
    keplerianElements: {
      a: 1.08209e8 / DISTANCE_SCALE_KM,
      e: 0.00676,
      inclination: 3.395,
      omega: 131.532,
      raan: 76.681,
      ma0: 50.415,
    },
    periodDays: 224.70,
  },

  earth: {
    id: 'earth',
    horizonsId: 399,
    name: 'Earth',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 6371.0,
    labelColor: '#4fb8ff',
    textures: {
      placeholder: '#4fb8ff',
      low: '/textures/lod/8k_earth_daymap_1k.jpg',
      high: '/textures/8k_earth_daymap.jpg',
    },
    keplerianElements: {
      a: 1.49598e8 / DISTANCE_SCALE_KM,
      e: 0.0167,
      inclination: 0.0,
      omega: 102.947,
      raan: -11.260,
      ma0: 357.517,
    },
    periodDays: 365.256,
  },

  moon: {
    id: 'moon',
    horizonsId: 301,
    name: 'Moon',
    type: 'moon',
    parentId: 'earth',
    radiusKm: 1737.4,
    labelColor: '#c8c8c8',
    textures: {
      placeholder: '#c8c8c8',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      // Distance from Earth (geocentric)
      a: 384400 / DISTANCE_SCALE_KM,
      e: 0.0549,
      inclination: 5.145,
      omega: 318.0,
      raan: 125.0,
      ma0: 135.27,
    },
    periodDays: 27.321582,
  },

  mars: {
    id: 'mars',
    horizonsId: 499,
    name: 'Mars',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 3389.5,
    labelColor: '#c1440e',
    textures: {
      placeholder: '#c1440e',
      low: '/textures/lod/8k_mars_1k.jpg',
      high: '/textures/8k_mars.jpg',
    },
    keplerianElements: {
      a: 2.27956e8 / DISTANCE_SCALE_KM,
      e: 0.0935,
      inclination: 1.848,
      omega: 336.04,
      raan: 49.579,
      ma0: 19.412,
    },
    periodDays: 686.980,
  },

  jupiter: {
    id: 'jupiter',
    horizonsId: 599,
    name: 'Jupiter',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 69911,
    labelColor: '#c88b3a',
    textures: {
      placeholder: '#c88b3a',
      low: '/textures/lod/8k_jupiter_1k.jpg',
      high: '/textures/8k_jupiter.jpg',
    },
    keplerianElements: {
      a: 7.78479e8 / DISTANCE_SCALE_KM,
      e: 0.0487,
      inclination: 1.305,
      omega: 14.754,
      raan: 100.556,
      ma0: 20.020,
    },
    periodDays: 4332.589,
  },

  saturn: {
    id: 'saturn',
    horizonsId: 699,
    name: 'Saturn',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 58232,
    labelColor: '#e4d191',
    textures: {
      placeholder: '#e4d191',
      low: '/textures/lod/8k_saturn_1k.jpg',
      high: '/textures/8k_saturn.jpg',
    },
    keplerianElements: {
      a: 14.32041e8 / DISTANCE_SCALE_KM,
      e: 0.0520,
      inclination: 2.486,
      omega: 92.432,
      raan: 113.715,
      ma0: 317.020,
    },
    periodDays: 10755.699,
  },

  uranus: {
    id: 'uranus',
    horizonsId: 799,
    name: 'Uranus',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 25362,
    labelColor: '#7de8e8',
    textures: {
      placeholder: '#7de8e8',
      low: '/textures/lod/2k_uranus_1k.jpg',
      high: '/textures/2k_uranus.jpg',
    },
    keplerianElements: {
      a: 28.67043e8 / DISTANCE_SCALE_KM,
      e: 0.0469,
      inclination: 0.770,
      omega: 170.964,
      raan: 74.230,
      ma0: 142.955,
    },
    periodDays: 30685.400,
  },

  neptune: {
    id: 'neptune',
    horizonsId: 899,
    name: 'Neptune',
    type: 'planet',
    parentId: 'sun',
    radiusKm: 24622,
    labelColor: '#3f54ba',
    textures: {
      placeholder: '#3f54ba',
      low: '/textures/lod/2k_neptune_1k.jpg',
      high: '/textures/2k_neptune.jpg',
    },
    keplerianElements: {
      a: 45.1495e8 / DISTANCE_SCALE_KM,
      e: 0.0097,
      inclination: 1.770,
      omega: 44.971,
      raan: 131.722,
      ma0: 259.905,
    },
    periodDays: 60189,
  },

  phobos: {
    id: 'phobos',
    horizonsId: 401,
    name: 'Phobos',
    type: 'moon',
    parentId: 'mars',
    radiusKm: 11.1,
    labelColor: '#9b8f84',
    textures: {
      placeholder: '#9b8f84',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 9376 / DISTANCE_SCALE_KM,
      e: 0.0151,
      inclination: 1.093,
      omega: 0,
      raan: 0,
      ma0: 35,
    },
    periodDays: 0.31891,
  },

  deimos: {
    id: 'deimos',
    horizonsId: 402,
    name: 'Deimos',
    type: 'moon',
    parentId: 'mars',
    radiusKm: 6.2,
    labelColor: '#aaa19a',
    textures: {
      placeholder: '#aaa19a',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 23463 / DISTANCE_SCALE_KM,
      e: 0.00033,
      inclination: 0.93,
      omega: 0,
      raan: 0,
      ma0: 140,
    },
    periodDays: 1.26244,
  },

  io: {
    id: 'io',
    horizonsId: 501,
    name: 'Io',
    type: 'moon',
    parentId: 'jupiter',
    radiusKm: 1821.6,
    labelColor: '#d9b15f',
    textures: {
      placeholder: '#d9b15f',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 421700 / DISTANCE_SCALE_KM,
      e: 0.0041,
      inclination: 0.05,
      omega: 0,
      raan: 0,
      ma0: 20,
    },
    periodDays: 1.76914,
  },

  europa: {
    id: 'europa',
    horizonsId: 502,
    name: 'Europa',
    type: 'moon',
    parentId: 'jupiter',
    radiusKm: 1560.8,
    labelColor: '#d8c7a4',
    textures: {
      placeholder: '#d8c7a4',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 671034 / DISTANCE_SCALE_KM,
      e: 0.0094,
      inclination: 0.47,
      omega: 0,
      raan: 0,
      ma0: 90,
    },
    periodDays: 3.55118,
  },

  ganymede: {
    id: 'ganymede',
    horizonsId: 503,
    name: 'Ganymede',
    type: 'moon',
    parentId: 'jupiter',
    radiusKm: 2634.1,
    labelColor: '#b6aa96',
    textures: {
      placeholder: '#b6aa96',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 1070412 / DISTANCE_SCALE_KM,
      e: 0.0013,
      inclination: 0.2,
      omega: 0,
      raan: 0,
      ma0: 180,
    },
    periodDays: 7.15455,
  },

  callisto: {
    id: 'callisto',
    horizonsId: 504,
    name: 'Callisto',
    type: 'moon',
    parentId: 'jupiter',
    radiusKm: 2410.3,
    labelColor: '#8d8170',
    textures: {
      placeholder: '#8d8170',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 1882709 / DISTANCE_SCALE_KM,
      e: 0.0074,
      inclination: 0.192,
      omega: 0,
      raan: 0,
      ma0: 270,
    },
    periodDays: 16.68902,
  },

  titan: {
    id: 'titan',
    horizonsId: 606,
    name: 'Titan',
    type: 'moon',
    parentId: 'saturn',
    radiusKm: 2574.7,
    labelColor: '#c99252',
    textures: {
      placeholder: '#c99252',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 1221870 / DISTANCE_SCALE_KM,
      e: 0.0288,
      inclination: 0.349,
      omega: 0,
      raan: 0,
      ma0: 60,
    },
    periodDays: 15.94542,
  },

  titania: {
    id: 'titania',
    horizonsId: 703,
    name: 'Titania',
    type: 'moon',
    parentId: 'uranus',
    radiusKm: 788.9,
    labelColor: '#b9b9b9',
    textures: {
      placeholder: '#b9b9b9',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 436300 / DISTANCE_SCALE_KM,
      e: 0.0011,
      inclination: 0.079,
      omega: 0,
      raan: 0,
      ma0: 145,
    },
    periodDays: 8.70587,
  },

  oberon: {
    id: 'oberon',
    horizonsId: 704,
    name: 'Oberon',
    type: 'moon',
    parentId: 'uranus',
    radiusKm: 761.4,
    labelColor: '#9c9994',
    textures: {
      placeholder: '#9c9994',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 583500 / DISTANCE_SCALE_KM,
      e: 0.0014,
      inclination: 0.068,
      omega: 0,
      raan: 0,
      ma0: 235,
    },
    periodDays: 13.46323,
  },

  triton: {
    id: 'triton',
    horizonsId: 801,
    name: 'Triton',
    type: 'moon',
    parentId: 'neptune',
    radiusKm: 1353.4,
    labelColor: '#d0c8bc',
    textures: {
      placeholder: '#d0c8bc',
      low: '/textures/lod/8k_moon_1k.jpg',
      high: '/textures/8k_moon.jpg',
    },
    keplerianElements: {
      a: 354759 / DISTANCE_SCALE_KM,
      e: 0.000016,
      inclination: 156.865,
      omega: 0,
      raan: 0,
      ma0: 310,
    },
    periodDays: 5.87685,
  },
};

/** All planet ids in order from Sun */
export const PLANET_IDS = [
  'mercury', 'venus', 'earth', 'mars',
  'jupiter', 'saturn', 'uranus', 'neptune',
] as const;

/** Major moon ids rendered when their parent planet is focused/nearby. */
export const MAJOR_MOON_IDS = [
  'moon',
  'phobos', 'deimos',
  'io', 'europa', 'ganymede', 'callisto',
  'titan',
  'titania', 'oberon',
  'triton',
] as const;

/** Top-level body ids that are safe to preload in the background. */
export const PRELOAD_BODY_IDS = [...PLANET_IDS, 'moon'] as const;

/** All body ids known to the app. */
export const ALL_BODY_IDS = [...PLANET_IDS, ...MAJOR_MOON_IDS] as const;
